In [1]:
# 4 x 3 x 130 x 750

In [2]:
import numpy as np

In [3]:
# one unit matrix, all zeros 13x15
unit_mat_13x25 = np.zeros((3,13,25), dtype=int)

In [5]:
# create a single row with 13 13x15 matrices
unit_row_13x750_list = []

# list of 10 13x15 matrices
for i in range(30):
  unit_row_13x750_list.append(unit_mat_13x25 + i)

In [8]:
# create a single row for one matrix
unit_row_13x750 = np.concatenate((tuple(unit_row_13x750_list)), axis=2)

In [9]:
unit_row_13x750.shape

(3, 13, 750)

In [17]:
# create multiple rows to create one base matrix
# Should be 10 instances of rows
# need to increment the values of each row by 30
# [0, 30,..., ]

unit_matrix_130x750_list = []
for i in np.arange(0,300,30):
  unit_matrix_130x750_list.append(unit_row_13x750 + i)

In [18]:
len(unit_matrix_130x750_list)

10

In [19]:
unit_matrix_130x750 = np.concatenate(tuple(unit_matrix_130x750_list), axis=1)

In [20]:
unit_matrix_130x750.shape

(3, 130, 750)

In [25]:
# sanity check
unit_matrix_130x750[1,12,:] # then when you do unit_matrix_130x750[1,13,:] you'll get everything incremented by 30

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9

In [26]:
unit_matrix_130x750[2,12,:]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9

In [27]:
unit_matrix_130x750[2,12,:]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9

In [28]:
unit_matrix_130x750[2,129,:]

array([270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270,
       270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 271,
       271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271,
       271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 272, 272,
       272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272,
       272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 273, 273, 273,
       273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273,
       273, 273, 273, 273, 273, 273, 273, 273, 273, 274, 274, 274, 274,
       274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274,
       274, 274, 274, 274, 274, 274, 274, 274, 275, 275, 275, 275, 275,
       275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275,
       275, 275, 275, 275, 275, 275, 275, 276, 276, 276, 276, 276, 276,
       276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276,
       276, 276, 276, 276, 276, 276, 277, 277, 277, 277, 277, 27

In [30]:
unit_matrix_130x750[2,129,:]

array([270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270,
       270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 270, 271,
       271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271,
       271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 271, 272, 272,
       272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 272,
       272, 272, 272, 272, 272, 272, 272, 272, 272, 272, 273, 273, 273,
       273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273, 273,
       273, 273, 273, 273, 273, 273, 273, 273, 273, 274, 274, 274, 274,
       274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274, 274,
       274, 274, 274, 274, 274, 274, 274, 274, 275, 275, 275, 275, 275,
       275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275, 275,
       275, 275, 275, 275, 275, 275, 275, 276, 276, 276, 276, 276, 276,
       276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276, 276,
       276, 276, 276, 276, 276, 276, 277, 277, 277, 277, 277, 27

In [ ]:
# need 4 base matrices to create one whole mask
# want 4 x 3 x 130 x 750

In [31]:
full_matrix_4x3x130x750_list = []
for i in np.arange(0, 1200, 300):
  full_matrix_4x3x130x750_list.append(unit_matrix_130x750 + i)

In [33]:
len(full_matrix_4x3x130x750_list)

4

In [35]:
full_matrix_4x3x130x750_list[1]

array([[[300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        ...,
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599]],

       [[300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        ...,
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599]],

       [[300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        [300, 300, 300, ..., 329, 329, 329],
        ...,
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599],
        [570, 570, 570, ..., 599, 599, 599]]])

In [45]:
full_matrix_3x4x130x750 = np.zeros((4,3,130,750))

In [46]:
for i in range(len(full_matrix_4x3x130x750_list)):
  full_matrix_3x4x130x750[i] = full_matrix_4x3x130x750_list[i]

In [50]:
full_matrix_3x4x130x750[3]

array([[[ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        ...,
        [1170., 1170., 1170., ..., 1199., 1199., 1199.],
        [1170., 1170., 1170., ..., 1199., 1199., 1199.],
        [1170., 1170., 1170., ..., 1199., 1199., 1199.]],

       [[ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        ...,
        [1170., 1170., 1170., ..., 1199., 1199., 1199.],
        [1170., 1170., 1170., ..., 1199., 1199., 1199.],
        [1170., 1170., 1170., ..., 1199., 1199., 1199.]],

       [[ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        [ 900.,  900.,  900., ...,  929.,  929.,  929.],
        ...,
        [1170., 1170., 1170., ..., 1199., 1199., 1199.],
        [1170., 1170., 1170., ..., 1199., 119

In [55]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [58]:
%ls drive/MyDrive/Fish\ Attribution

'Feature Mask Engineering.ipynb'
'Full DeepLIFT Attribution Generation.ipynb'
'Full Integrated Gradients Attribution Generation.ipynb'
'Full Interactive Integrated Gradients.ipynb'
'Full Shapley Value Sampling.ipynb'
 model1e-05500.5_april_4.pt
'x_train_b_cropped (1).npy'
 x_train_b_cropped_integrated_gradients.tensor
 x_train_b_cropped.npy
 y_train_b.npy


In [61]:
# save the mask
np.save("drive/MyDrive/Fish Attribution" + "/13x25 Mask", full_matrix_3x4x130x750)